apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-operator-repo
spec:
  interval: 10m
  url: https://github.com/morten-olsen/homelab-operator
  ref:
    branch: main