apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  targetNamespace: cert-manager
  interval: 1h
  install:
    createNamespace: true
  values:
    installCRDs: true
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: jetstack-repo
      version: v1.18.2