apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  targetNamespace: local-path-storage
  interval: 1h
  install:
    createNamespace: true
  values:
    storageClass:
      name: local-path
      provisionerName: rancher.io/local-path
      defaultClass: true
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - {{ .Values.storagePath }}
    helper:
      reclaimPolicy: Retain
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: containerro-repo
