apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  targetNamespace: istio-system
  interval: 1h
  install:
    createNamespace: true
  dependsOn:
    - name: istio-base
      namespace: "{{ .Release.Namespace }}"
  chart:
    spec:
      chart: istiod
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: istio-repo
      reconcileStrategy: ChartVersion
      version: 1.24.3