apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ .Release.Name }}"
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "{{ .Release.Namespace }}"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
