apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: authentik
spec:
  host: authentik-server.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE